### ISSUE TITLE
When will a new release be published?

### ISSUE THREAD

**Issue by JakeChampion** [paulmillr/Array.prototype.findIndex#14]
Some changes have been added to master which have not been published as an update for the module. Would you be able to give a date for when these changes will be published?

**Comment by JakeChampion** [comment]
Would you be able to publish a new release please?

**Comment by ljharb** [comment]
@paulmillr I don't have `npm owner` on this package, or I'd take care of it - would you mind cutting a release?

**Comment by paulmillr** [comment]
@ljharb done, you are now owner of both packages

**Comment by ljharb** [comment]
Thanks!

**Comment by ljharb** [comment]
@paulmillr it'd be cool if i was a collab on both of the repos as well, so I don't have to bug you to merge PRs and close issues :-)

**Comment by paulmillr** [comment]
:+1:

**Comment by ljharb** [comment]
Published at 60163ec9a30eb864c981d7ca45ea3eff8cee93fe as v2.0.0
