### ISSUE TITLE
Code repetition?

### ISSUE THREAD

**Issue by Xotic750** [paulmillr/Array.prototype.findIndex#16]
https://github.com/paulmillr/Array.prototype.findIndex/blob/master/implementation.js#L8

Any reason for calling ToLength twice?

**Comment by ljharb** [comment]
Not that I can see; that first appeared in https://github.com/paulmillr/Array.prototype.findIndex/commit/72354b31cfad80dc34c8bce001bb23620ee3c93d with no explanation.
